package cmd

import (
	"fmt"
	"net"
	"strconv"
	"strings"
	"time"

	"paas-cli/internal/api"
)

// The local half of `connect --local`: which loopback address stands in for
// which database, and what that does to the site's variables. Both are pure so
// the numbering and the rewriting are testable without binding a port.

// localListener is one database reachable at a loopback address for as long as
// the command runs.
type localListener struct {
	Target api.TunnelTarget
	Addr   string
}

// listenerBase is where each database kind starts numbering: the engine's
// default port plus 10000, so a local postgres on 5432 and the tunnel's 15432
// never collide and the number still says what is behind it.
func listenerBase(kind string) int {
	switch kind {
	case "mongodb":
		return 15017
	case "postgres":
		return 15432
	default:
		return 15100
	}
}

// planListeners picks one loopback address per target, counting up from the
// kind's base and stepping over ports the probe reports busy. Ports already
// handed out in this plan are busy too — nothing is bound yet, so the probe
// cannot know about them.
func planListeners(targets []api.TunnelTarget, free func(port int) bool) []localListener {
	taken := map[int]bool{}
	listeners := make([]localListener, 0, len(targets))
	for _, target := range targets {
		port := listenerBase(target.Kind)
		for taken[port] || !free(port) {
			port++
		}
		taken[port] = true
		listeners = append(listeners, localListener{Target: target, Addr: net.JoinHostPort("127.0.0.1", strconv.Itoa(port))})
	}
	return listeners
}

// portFree reports whether a loopback port can be listened on right now. A
// port something else holds is refused here rather than half-way through the
// command.
func portFree(port int) bool {
	ln, err := net.Listen("tcp", net.JoinHostPort("127.0.0.1", strconv.Itoa(port)))
	if err != nil {
		return false
	}
	ln.Close()
	return true
}

// rewriteEnvForLocal copies env with every in-cluster database address
// replaced by its listener, and reports which keys changed. Matching on the
// exact host:port leaves connection strings otherwise intact — credentials,
// database name and every option ride along untouched — and touches the
// per-database `_<SEGMENT>` variants for free.
func rewriteEnvForLocal(env map[string]string, ls []localListener) (map[string]string, []string) {
	out := make(map[string]string, len(env))
	for k, v := range env {
		out[k] = v
	}
	var changed []string
	for _, k := range sortedKeys(out) {
		value := out[k]
		for _, l := range ls {
			remote := net.JoinHostPort(l.Target.Host, strconv.Itoa(l.Target.Port))
			value = strings.ReplaceAll(value, remote, l.Addr)
		}
		if value != out[k] {
			out[k] = value
			changed = append(changed, k)
		}
	}
	return out, changed
}

// localHeader is the dotenv header: where the file came from, which database
// each rewritten address is, and that the addresses only answer while the
// command runs.
func localHeader(projectName, siteSlug string, ls []localListener) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `ghayma connect --local` for %s/%s on %s\n", projectName, siteSlug, time.Now().UTC().Format(time.RFC3339))
	b.WriteString("# The site's effective variables, with the databases pointing at this machine:\n")
	for _, l := range ls {
		fmt.Fprintf(&b, "#   %s (%s) → %s\n", l.Target.Name, l.Target.Kind, l.Addr)
	}
	b.WriteString("# Those addresses answer only while `ghayma connect --local` runs. Contains secrets — keep this file out of git.\n")
	return b.String()
}
