package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"paas-cli/internal/api"
	"paas-cli/internal/config"

	"github.com/spf13/cobra"
)

var (
	envPullOut   string
	envPullForce bool
)

var envPullCmd = &cobra.Command{
	Use:   "pull",
	Short: "Write the site's effective variables to a local dotenv file",
	Long: `Write the site's EFFECTIVE environment to a local dotenv file: the
variables you set plus every value the platform derives from the site's
connections — database URLs, storage credentials, the auth app's variables,
cron secrets and the managed platform key. It is exactly what the deployed
app receives, so your local app runs against the same services.

The file is .env.local next to the app (its directory in a workspace), or
--out. The values are secrets: the command refuses a file git tracks,
refuses one git does not ignore unless --force, writes it readable by you
only, and never prints a value. Needs the project admin role; every pull is
recorded in the project's audit log.

Examples:
  ghayma env pull
  ghayma env pull --site admin --out .env.development.local`,
	Args: cobra.NoArgs,
	Run:  runEnvPull,
}

// dotenvQuote renders a value so every dotenv dialect (dotenv, @next/env with
// dotenv-expand, godotenv, python-dotenv, docker compose, a shell `source`)
// reads it back literally. Single quotes are the only form none of them
// expand or unescape, so they are the default; a value holding a single
// quote or a line break falls back to double quotes with the escapes those
// dialects agree on.
func dotenvQuote(v string) string {
	if !strings.ContainsAny(v, "'\n\r") {
		return "'" + v + "'"
	}
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\r", `\r`)
	return `"` + r.Replace(v) + `"`
}

// renderDotenv writes the header then KEY=value lines in key order, so two
// pulls of the same site diff cleanly.
func renderDotenv(header string, env map[string]string) string {
	var b strings.Builder
	b.WriteString(header)
	if !strings.HasSuffix(header, "\n") {
		b.WriteString("\n")
	}
	for _, k := range sortedKeys(env) {
		b.WriteString(k)
		b.WriteString("=")
		b.WriteString(dotenvQuote(env[k]))
		b.WriteString("\n")
	}
	return b.String()
}

func pullHeader(projectName, siteSlug string) string {
	return fmt.Sprintf("# Generated by `ghayma env pull` for %s/%s on %s\n# Effective variables: exactly what the deployed app receives. Contains secrets — keep this file out of git.\n",
		projectName, siteSlug, time.Now().UTC().Format(time.RFC3339))
}

// envPullRefusal decides whether writing the file is safe. A tracked file is
// never written — the next commit would publish every secret. Inside a
// repository an unignored file is refused too unless --force, since
// `git add .` would stage it.
func envPullRefusal(tracked, ignored, inRepo, force bool, name string) error {
	if tracked {
		return fmt.Errorf("%s is tracked by git — the secrets would land in your next commit. Untrack it (git rm --cached %s), add it to .gitignore, then re-run", name, name)
	}
	if inRepo && !ignored && !force {
		return fmt.Errorf("%s is not git-ignored — add it (echo '%s' >> .gitignore) or pass --force to write it anyway", name, name)
	}
	return nil
}

// gitFileState asks git whether the path is tracked and whether it is ignored.
// No git on PATH, or no repository, reads as "not in a repository": nothing
// can be tracked there. Exit codes: ls-files --error-unmatch is 0 iff tracked;
// check-ignore is 0 iff ignored, 1 iff not, 128 outside a repository.
func gitFileState(path string) (tracked, ignored, inRepo bool) {
	dir, name := filepath.Split(path)
	if dir == "" {
		dir = "."
	}
	run := func(args ...string) (int, bool) {
		cmd := exec.Command("git", append([]string{"-C", dir}, args...)...)
		cmd.Stdout, cmd.Stderr = nil, nil
		if err := cmd.Run(); err != nil {
			if exit, ok := err.(*exec.ExitError); ok {
				return exit.ExitCode(), true
			}
			return -1, false // git missing or unrunnable
		}
		return 0, true
	}
	code, ran := run("ls-files", "--error-unmatch", "--", name)
	if !ran || code == 128 {
		return false, false, false
	}
	tracked = code == 0
	code, ran = run("check-ignore", "-q", "--", name)
	if !ran || code == 128 {
		return tracked, false, tracked
	}
	return tracked, code == 0, true
}

func runEnvPull(cmd *cobra.Command, args []string) {
	cfg := config.Load()
	if !cfg.LoggedIn() {
		failf("Please login first: ghayma login")
		return
	}
	client := api.NewClient(cfg)
	target, err := resolveConnectionTarget(client, envSite, "pull env vars for")
	if err != nil {
		reportSiteError(err)
		exitFn(1)
		return
	}

	out := envPullOut
	if out == "" {
		out = filepath.Join(target.AppDir, ".env.local")
	} else if !filepath.IsAbs(out) {
		cwd, _ := os.Getwd()
		out = filepath.Join(cwd, out)
	}
	tracked, ignored, inRepo := gitFileState(out)
	if err := envPullRefusal(tracked, ignored, inRepo, envPullForce, filepath.Base(out)); err != nil {
		failf("%v", err)
		return
	}

	env, err := client.GetEffectiveSiteEnv(target.ProjectID, target.Site.ID)
	if err != nil {
		switch {
		case strings.Contains(err.Error(), "insufficient role"):
			failf("The project admin role is needed to pull effective variables (they include service credentials) — ask the project owner")
			return
		case strings.Contains(err.Error(), "404 page not found"):
			// A bare 404 is the route itself missing: a CLI released ahead of the
			// platform update, not a site or project that is not there.
			failf("This platform does not serve effective variables yet — the update that adds them is not deployed. Until then: ghayma env list")
			return
		}
		failf("Failed to pull env vars: %v", err)
		return
	}

	data := renderDotenv(pullHeader(target.ProjectName, target.Site.Slug), env)
	if err := os.WriteFile(out, []byte(data), 0o600); err != nil {
		failf("Failed to write %s: %v", out, err)
		return
	}

	shown := out
	if cwd, err := os.Getwd(); err == nil {
		if rel, err := filepath.Rel(cwd, out); err == nil && !strings.HasPrefix(rel, "..") {
			shown = rel
		}
	}
	fmt.Printf("✅ Wrote %d variables for '%s' to %s\n", len(env), target.Site.Slug, shown)
	for _, k := range sortedKeys(env) {
		fmt.Printf("   %s\n", k)
	}
	fmt.Println("\n   Contains secrets — keep it out of git. Values are never printed here; open the file.")
}
